# Data
data_dir: "/data/cars_196"
annotations_path: "/data/cars_196/cars_annos.mat"

log_path: "/tmp/logs/log.html"

train:
    categories_per_batch: 10
    samples_per_category: 8

# Size at which model expects images to be
image_size: 224

model_dir: "/data/image_retrieval/current_model/"